// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	er "github.com/exluap/kit/er"
	mock "github.com/stretchr/testify/mock"
)

// AppErrBuilder is an autogenerated mock type for the AppErrBuilder type
type AppErrBuilder struct {
	mock.Mock
}

// C provides a mock function with given fields: ctx
func (_m *AppErrBuilder) C(ctx context.Context) er.AppErrBuilder {
	ret := _m.Called(ctx)

	var r0 er.AppErrBuilder
	if rf, ok := ret.Get(0).(func(context.Context) er.AppErrBuilder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(er.AppErrBuilder)
		}
	}

	return r0
}

// Err provides a mock function with given fields:
func (_m *AppErrBuilder) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// F provides a mock function with given fields: fields
func (_m *AppErrBuilder) F(fields er.FF) er.AppErrBuilder {
	ret := _m.Called(fields)

	var r0 er.AppErrBuilder
	if rf, ok := ret.Get(0).(func(er.FF) er.AppErrBuilder); ok {
		r0 = rf(fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(er.AppErrBuilder)
		}
	}

	return r0
}

// GrpcSt provides a mock function with given fields: status
func (_m *AppErrBuilder) GrpcSt(status uint32) er.AppErrBuilder {
	ret := _m.Called(status)

	var r0 er.AppErrBuilder
	if rf, ok := ret.Get(0).(func(uint32) er.AppErrBuilder); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(er.AppErrBuilder)
		}
	}

	return r0
}

// HttpSt provides a mock function with given fields: status
func (_m *AppErrBuilder) HttpSt(status uint32) er.AppErrBuilder {
	ret := _m.Called(status)

	var r0 er.AppErrBuilder
	if rf, ok := ret.Get(0).(func(uint32) er.AppErrBuilder); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(er.AppErrBuilder)
		}
	}

	return r0
}
