// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	log "github.com/exluap/kit/log"
	mock "github.com/stretchr/testify/mock"
)

// CLoggerFunc is an autogenerated mock type for the CLoggerFunc type
type CLoggerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *CLoggerFunc) Execute() log.CLogger {
	ret := _m.Called()

	var r0 log.CLogger
	if rf, ok := ret.Get(0).(func() log.CLogger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.CLogger)
		}
	}

	return r0
}
