// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	cron "github.com/exluap/kit/cron"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, name
func (_m *Manager) Add(ctx context.Context, name string) cron.Cron {
	ret := _m.Called(ctx, name)

	var r0 cron.Cron
	if rf, ok := ret.Get(0).(func(context.Context, string) cron.Cron); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cron.Cron)
		}
	}

	return r0
}

// Start provides a mock function with given fields: ctx
func (_m *Manager) Start(ctx context.Context) {
	_m.Called(ctx)
}

// Stop provides a mock function with given fields: ctx
func (_m *Manager) Stop(ctx context.Context) {
	_m.Called(ctx)
}
