// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	monitoring "github.com/exluap/kit/monitoring"
	mock "github.com/stretchr/testify/mock"
)

// MetricsServer is an autogenerated mock type for the MetricsServer type
type MetricsServer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MetricsServer) Close() {
	_m.Called()
}

// Init provides a mock function with given fields: config, MetricProviders
func (_m *MetricsServer) Init(config *monitoring.Config, MetricProviders ...monitoring.MetricsProvider) error {
	_va := make([]interface{}, len(MetricProviders))
	for _i := range MetricProviders {
		_va[_i] = MetricProviders[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, config)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*monitoring.Config, ...monitoring.MetricsProvider) error); ok {
		r0 = rf(config, MetricProviders...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Listen provides a mock function with given fields:
func (_m *MetricsServer) Listen() {
	_m.Called()
}
