// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	monitoring "github.com/exluap/kit/monitoring"
	mock "github.com/stretchr/testify/mock"
)

// MetricsProvider is an autogenerated mock type for the MetricsProvider type
type MetricsProvider struct {
	mock.Mock
}

// GetCollector provides a mock function with given fields:
func (_m *MetricsProvider) GetCollector() monitoring.MetricsCollector {
	ret := _m.Called()

	var r0 monitoring.MetricsCollector
	if rf, ok := ret.Get(0).(func() monitoring.MetricsCollector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(monitoring.MetricsCollector)
		}
	}

	return r0
}
