// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	listener "github.com/exluap/kit/queue/listener"
	mock "github.com/stretchr/testify/mock"

	queue "github.com/exluap/kit/queue"
)

// QueueListener is an autogenerated mock type for the QueueListener type
type QueueListener struct {
	mock.Mock
}

// Add provides a mock function with given fields: qt, topic, h
func (_m *QueueListener) Add(qt queue.QueueType, topic string, h ...listener.QueueMessageHandler) {
	_va := make([]interface{}, len(h))
	for _i := range h {
		_va[_i] = h[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, qt, topic)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// AddLb provides a mock function with given fields: qt, topic, lbGroup, h
func (_m *QueueListener) AddLb(qt queue.QueueType, topic string, lbGroup string, h ...listener.QueueMessageHandler) {
	_va := make([]interface{}, len(h))
	for _i := range h {
		_va[_i] = h[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, qt, topic, lbGroup)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Clear provides a mock function with given fields:
func (_m *QueueListener) Clear() {
	_m.Called()
}

// ListenAsync provides a mock function with given fields:
func (_m *QueueListener) ListenAsync() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *QueueListener) Stop() {
	_m.Called()
}
