// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	service "github.com/exluap/kit/service"
	mock "github.com/stretchr/testify/mock"
)

// Raft is an autogenerated mock type for the Raft type
type Raft struct {
	mock.Mock
}

// AmILeader provides a mock function with given fields:
func (_m *Raft) AmILeader() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *Raft) Close() {
	_m.Called()
}

// Init provides a mock function with given fields: opt, ev
func (_m *Raft) Init(opt *service.Options, ev service.OnLeaderChangedEvent) error {
	ret := _m.Called(opt, ev)

	var r0 error
	if rf, ok := ret.Get(0).(func(*service.Options, service.OnLeaderChangedEvent) error); ok {
		r0 = rf(opt, ev)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *Raft) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
